"use client";

import { useState } from "react";
import { boardStats, type Newsletter, type NewsletterStatus } from "../data/mock";
import { Avatar, Boardmark } from "./Boardmark";
import { ShareCard } from "./ShareCard";
import { capture } from "@/lib/posthog";

type ClaimFlowProps = { open: boolean; onClose: () => void; initialNewsletter?: Newsletter };
type Step = "url" | "preview" | "ownership" | "success" | "profile";
type ApiResult = { error?: string; newsletter?: { normalizedUrl: string; title: string; canonicalUrl: string; description?: string | null; contactEmail?: string | null }; claim?: { confirmationUrl?: string } };

const demoNewsletter: Newsletter = { id: "new-newsletter", name: "The Daily Signal", url: "thedailysignal.co", description: "A sharp daily briefing for people building what comes next.", category: "Technology", bid: 0, clicks: 0, lastSeen: "just now", initials: "T", tone: "ink", status: "pending" };
function stepLabel(step: Step) { if (step === "url") return "01 / ADD URL"; if (step === "preview") return "02 / REVIEW DETAILS"; if (step === "ownership") return "03 / CONFIRM OWNERSHIP"; return "04 / YOU ARE ON THE BOARD"; }

export function ClaimFlow({ open, onClose, initialNewsletter }: ClaimFlowProps) {
  const [step, setStep] = useState<Step>(initialNewsletter ? "profile" : "url");
  const [value, setValue] = useState(initialNewsletter?.url ?? "");
  const [newsletter, setNewsletter] = useState<Newsletter>(initialNewsletter ?? demoNewsletter);
  const [status, setStatus] = useState<NewsletterStatus>(initialNewsletter?.status ?? "pending");
  const [copied, setCopied] = useState(false);
  const [claimUrl, setClaimUrl] = useState<string>();
  const [publicContactEmail, setPublicContactEmail] = useState<string>();
  const [error, setError] = useState<string>();
  if (open && step === "url") capture("claim_started");
  if (!open) return null;
  async function handleUrlSubmit(event: React.FormEvent) { event.preventDefault(); if (!value.trim()) return; capture("url_submitted"); setError(undefined); try { const response = await fetch("/api/newsletters/resolve", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ url: value }) }); const result = await response.json() as ApiResult; if (!response.ok || !result.newsletter) throw new Error(result.error ?? "METADATA_UNAVAILABLE"); capture("metadata_loaded"); const item = result.newsletter; setPublicContactEmail(item.contactEmail ?? undefined); setNewsletter({ ...demoNewsletter, id: item.normalizedUrl, name: item.title, url: item.canonicalUrl, description: item.description ?? "A public newsletter on Letterboard.", initials: item.title.slice(0, 1).toUpperCase(), status: "pending" }); setStatus("pending"); setStep("preview"); } catch (caught) { capture("metadata_failed"); setError(caught instanceof Error ? caught.message : "METADATA_UNAVAILABLE"); } }
  async function createClaim() { setError(undefined); try { const parsed = new URL(newsletter.url.startsWith("http") ? newsletter.url : `https://${newsletter.url}`); const normalizedUrl = `${parsed.hostname.replace(/^www\./, "")}${parsed.pathname.replace(/\/+$/, "") || "/"}`; const response = await fetch("/api/claims", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ newsletter: { canonicalUrl: parsed.toString(), normalizedUrl, title: newsletter.name, description: newsletter.description }, submittedUrl: value, contactEmail: publicContactEmail }) }); const result = await response.json() as ApiResult; if (!response.ok || !result.claim) throw new Error(result.error ?? "CLAIM_FAILED"); if (result.claim.confirmationUrl) setClaimUrl(result.claim.confirmationUrl); setStep("ownership"); } catch (caught) { setError(caught instanceof Error ? caught.message : "CLAIM_FAILED"); } }
  async function confirmOwnership() { if (!claimUrl) return; const response = await fetch(claimUrl); const result = await response.json() as ApiResult; if (!response.ok) { setError(result.error ?? "CONFIRMATION_FAILED"); return; } setStatus("confirmed"); setStep("success"); }
  async function copyShareMessage() { const message = `I just locked in Founding 100 status for ${newsletter.name} on @letterboard — free profile, first 100 on the board.\n\nletterboard.co/${newsletter.url.split(".")[0]}`; if (typeof navigator !== "undefined" && navigator.clipboard) await navigator.clipboard.writeText(message); setCopied(true); window.setTimeout(() => setCopied(false), 1800); }

  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.currentTarget === event.target) onClose(); }}><section className="claim-modal" role="dialog" aria-modal="true" aria-labelledby="claim-title">
    <header className="claim-modal__header"><div><p className="eyebrow">{stepLabel(step)}</p><h2 id="claim-title">{step === "success" ? "You are on the board." : step === "profile" ? "Public profile preview" : "Claim your Founding 100 place."}</h2></div><button className="icon-button" onClick={onClose} aria-label="Close claim flow">×</button></header>
    <div className="progress-dots" aria-label={`Step ${stepLabel(step)}`}>{["url", "preview", "ownership", "success"].map((item, index) => <span key={item} className={`progress-dot ${["url", "preview", "ownership", "success"].indexOf(step) >= index ? "progress-dot--active" : ""}`} />)}</div>
    {step === "url" && <div className="claim-step claim-step--url"><div className="claim-step__copy"><p className="hero-label">FOUNDING 100 / FREE CLAIM</p><h3>Put your newsletter on the board.</h3><p>Share a URL. We will pull the public details into a profile for you. No payment, no exclusivity, no commitment.</p></div><form onSubmit={handleUrlSubmit} className="url-form"><label htmlFor="newsletter-url">Newsletter URL</label><div className="url-input-wrap"><span>↗</span><input id="newsletter-url" value={value} onChange={(event) => setValue(event.target.value)} placeholder="https://yournewsletter.com" autoFocus /><button type="submit">Find my newsletter <span>→</span></button></div><p className="form-note">Try <button type="button" onClick={() => setValue("thedailysignal.co")}>thedailysignal.co</button> to preview the flow.</p></form><div className="reassurance-row"><span className="reassurance-icon">✓</span><span>We only use public information. Your profile stays pending until ownership is confirmed.</span></div></div>}
    {step === "preview" && <div className="claim-step"><div className="split-step"><div><p className="hero-label">DETAILS AUTO-FILLED</p><h3>We found your newsletter.</h3><p>Check the public details below. You can update them later from your creator profile.</p><div className="auto-fill-note"><span className="auto-fill-check">✓</span><span><strong>Newsletter found</strong><br />The URL resolves and public metadata is ready.</span></div><button className="primary-button" onClick={createClaim}>Continue <span>→</span></button><button className="secondary-button" onClick={() => setStep("url")}>Use a different URL</button></div><div className="preview-panel"><span className="preview-panel__label">PUBLIC PROFILE PREVIEW</span><div className="profile-heading"><Avatar initials={newsletter.initials} tone={newsletter.tone} /><div><h4>{newsletter.name}</h4><p>{newsletter.category}</p></div></div><Boardmark status="pending" /><div className="preview-divider" /><p>{newsletter.description}</p><span className="preview-url">{newsletter.url}</span></div></div><div className="reassurance-row"><span className="reassurance-icon">◎</span><span>This creates a free pending profile. The Founding 100 badge activates after one-click ownership confirmation.</span></div>{error && <p className="form-note" role="alert">{error}</p>}</div>}
    {step === "ownership" && <div className="claim-step"><div className="ownership-layout"><div className="ownership-icon">✉</div><div><p className="hero-label">ONE-CLICK CONFIRMATION</p><h3>Confirm that you run this newsletter.</h3><p>We will send a confirmation link to the public contact address we found for <strong>{newsletter.name}</strong>. Nothing to paste into your site, bio, or DNS.</p><div className="email-preview"><span className="email-preview__dot" /><div><strong>Confirmation email queued</strong><span>Sent to the public contact for {newsletter.url}</span></div><span className="email-preview__status">READY</span></div><div className="button-stack"><button className="primary-button" onClick={confirmOwnership}>Confirm ownership <span>→</span></button><button className="secondary-button" onClick={() => { setStep("success"); setStatus("pending"); }}>Keep profile pending</button></div>{error && <p className="form-note" role="alert">{error}</p>}</div></div></div>}
    {step === "success" && <div className="claim-step success-step"><div className="success-hero"><span className="success-check">✓</span><p className="hero-label">{status === "confirmed" ? "OWNERSHIP CONFIRMED" : "PROFILE RESERVED"}</p><h3>{status === "confirmed" ? "Founding 100 is yours." : "Your place is reserved."}</h3><p>{status === "confirmed" ? "Your Boardmark is active and your public profile is ready to share." : "Your profile is live as pending. Confirm ownership from the email whenever you are ready."}</p><Boardmark status={status} size="large" /></div><div className="success-position"><span className="success-position__rank">#{String(boardStats.claimed + 1).padStart(2, "0")}</span><div><strong>{newsletter.name}</strong><span>Founding place / 100</span></div><span className="success-position__status">{status === "confirmed" ? "ACTIVE" : "PENDING"}</span></div><div className="success-actions"><button className="primary-button" onClick={copyShareMessage}>{copied ? "Copied share message ✓" : "Share your place"} <span>↗</span></button><button className="secondary-button" onClick={() => setStep("profile")}>Preview public profile <span>→</span></button></div><p className="optional-note">Sharing is optional. It helps the board become visible; it does not gate your place.</p></div>}
    {step === "profile" && <div className="claim-step profile-step"><div className="profile-preview-header"><div><p className="hero-label">PUBLIC PROFILE</p><h3>{newsletter.name}</h3><p>{newsletter.url}</p></div><Boardmark status={status} /></div><div className="profile-preview-card"><div className="profile-preview-card__main"><Avatar initials={newsletter.initials} tone={newsletter.tone} /><div><span className="profile-preview-card__category">{newsletter.category}</span><h4>{newsletter.name}</h4><p>{newsletter.description}</p></div></div><div className="profile-preview-card__meta"><span><strong>#{String(boardStats.claimed + 1).padStart(2, "0")}</strong><small>Founding place</small></span><span><strong>{status === "confirmed" ? "Ready" : "Pending"}</strong><small>Boardmark</small></span></div></div><div className="profile-share-preview"><div><p className="hero-label">SHARE CARD</p><h4>Make your place visible.</h4><p>Use the same profile details and Boardmark everywhere you share it.</p></div><ShareCard name={newsletter.name} url={newsletter.url} category={newsletter.category} description={newsletter.description} rank={boardStats.claimed + 1} status={status} initials={newsletter.initials} tone={newsletter.tone} /></div><div className="success-actions"><button className="primary-button" onClick={copyShareMessage}>{copied ? "Copied share message ✓" : "Copy share message"}</button><button className="secondary-button" onClick={onClose}>Done</button></div></div>}
  </section></div>;
}
